name: Feature request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: [enhancement]
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version does this apply to?
      options:
        - 1.0
        - 2.0
        - 3.0
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Please describe what the problem is.
    validations:
      required: true
