name: Updating change log

on:
  pull_request:
    branches:
      - "main"
    types:
      - closed

jobs:
  updating-change-log:
    runs-on: ubuntu-latest
    name: Updating change log
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Starting changelogger 
        id: action
        uses: AntonioGally/ag-changelogger/@main
        with:
          changelogPath: ./CHANGELOG.md
          commitUserName: AntonioGally
          commitEmail: antonio.gally@gmail.com
