name: PR Inputs
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  input:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: |
          cd .github/scripts
          npm install @actions/core

      - name: Run inputs script
        run: node .github/scripts/inputs.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
