name: Labeler

on:
  pull_request:
    types:
      - closed
      - opened
      - edited

jobs:
  labeling-pr:
    runs-on: ubuntu-latest
    name: Adding label to pr
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run label CI
        id: action
        uses: AntonioGally/ag-pr-labeler/main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
