name: PR Labeler based on commit messages
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  labeler:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref != 'develop' && github.event.pull_request.base.ref != 'cloud002'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: |
          cd .github/scripts
          npm install @octokit/core
          npm install @actions/github

      - name: Run labeler script
        run: node .github/scripts/labeler.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        